### ISSUE TITLE
GG

### ISSUE THREAD

**Issue by hackerlor84** [shaddy43/BrowserSnatch#3]
Hello!
It looks like it can get the data but it's all encrypted.
I'm really interested in this project, I hope you will develop it in the future
![image](https://github.com/user-attachments/assets/56e8a70f-4e70-4324-a9f4-403db0ef7691)

**Comment by shaddy43** [comment]
BrowserSnatch creates an sqlite database file. If you open it in text editor, it will always show you null characters. I suggest you open it in db browser for sqlite (https://sqlitebrowser.org) and go to Browse Data tab to explore all tables (logins, cookies, history, bookmarks). 

BrowserSnatch is able to fetch and decrypt all passwords & cookies that are secured with v10 encryption. The introduction of latest chrome's app bound encryption (v20) has limited its capabilities but work is in progress and updates will be coming!

**Comment by hackerlor84** [comment]
I wish I could be a little smarter to help with this project, I'm the type of person who studies first and then immediately forgets it after a nap. Great job, man

**Comment by shaddy43** [comment]
Good luck, Keep learning :)
